# Generated by Django 5.0 on 2023-12-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='root_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
